from pathlib import Path
import sys,json,struct,copy,hashlib,numpy as np
sys.path.insert(0,str(Path(__file__).resolve().parent));from render_cached import GLB,norm
D=Path(__file__).resolve().parents[1];g=GLB(D/'model/kea_reference_shape.glb');base=g.j;doc=copy.deepcopy(base);binary=bytearray(g.bin);data=json.loads((D/'kea_motion_clips.json').read_text())
def add(values,kind):
 v=np.asarray(values,dtype='<f4');binary.extend(b'\0'*((-len(binary))%4));off=len(binary);binary.extend(v.tobytes());bv=len(doc['bufferViews']);doc['bufferViews'].append({'buffer':0,'byteOffset':off,'byteLength':v.nbytes});ac={'bufferView':bv,'componentType':5126,'count':len(v),'type':kind}
 if kind in ['SCALAR','VEC3']:
  ac['min']=[float(v.min())]if kind=='SCALAR'else v.min(0).tolist();ac['max']=[float(v.max())]if kind=='SCALAR'else v.max(0).tolist()
 k=len(doc['accessors']);doc['accessors'].append(ac);return k
P=np.fromfile(D/'model/actual_position_1.bin','<f4').reshape(-1,3);N=np.fromfile(D/'model/actual_normal_1.bin','<f4').reshape(-1,3);shape=json.loads((D/'kea_motion_shape.json').read_text());ix=np.array(shape['indices']);a=1-np.array(shape['wingInfluence']);pf=g.acc(0);nf=g.acc(1);delta=np.array(shape['deltaPosition']).reshape(-1,3);cn=np.array(shape['correctedNormal']).reshape(-1,3);pf[ix]+=delta*a[:,None];nf[ix]=norm(nf[ix]*(1-a[:,None])+cn*a[:,None]);deltaP=pf-P;deltaN=nf-N
prim=doc['meshes'][0]['primitives'][0];prim['attributes']['POSITION']=add(P,'VEC3');prim['attributes']['NORMAL']=add(N,'VEC3');prim['targets']=[{'POSITION':add(deltaP,'VEC3'),'NORMAL':add(deltaN,'VEC3')}];doc['meshes'][0]['weights']=[0.];doc['meshes'][0].setdefault('extras',{})['targetNames']=['flight_wing_release'];meshnode=next(i for i,n in enumerate(doc['nodes'])if n.get('mesh')==0)
_,trs=g.matrices(3.5);idleFrame={str(i):{k:v.tolist()for k,v in trs[i].items()}for i in g.j['skins'][0]['joints']};idle={'name':'approved_idle','duration':1.,'loop':True,'times':[0.,1.],'frames':[idleFrame,idleFrame],'wingRestWeight':1.,'events':[]}
clips=[idle]+data['clips'];exports=[]
for clip in clips:
 times=add(clip['times'],'SCALAR');anim={'name':clip['name'],'samplers':[],'channels':[],'extras':{'loop':clip['loop'],'events':clip['events']}}
 for id in data['nodes']:
  for path,kind in [('translation','VEC3'),('rotation','VEC4'),('scale','VEC3')]:
   out=add([f[id][path]for f in clip['frames']],kind);si=len(anim['samplers']);anim['samplers'].append({'input':times,'output':out,'interpolation':'LINEAR'});anim['channels'].append({'sampler':si,'target':{'node':int(id),'path':path}})
 out=add([1-clip['wingRestWeight']]*len(clip['times']),'SCALAR');si=len(anim['samplers']);anim['samplers'].append({'input':times,'output':out,'interpolation':'LINEAR'});anim['channels'].append({'sampler':si,'target':{'node':meshnode,'path':'weights'}});doc['animations'].append(anim);exports.append(clip['name'])
doc['buffers'][0]['byteLength']=len(binary);j=json.dumps(doc,separators=(',',':')).encode();j+=b' '*((-len(j))%4);binary.extend(b'\0'*((-len(binary))%4));raw=struct.pack('<III',0x46546c67,2,28+len(j)+len(binary))+struct.pack('<II',len(j),0x4e4f534a)+j+struct.pack('<II',len(binary),0x004e4942)+binary;(D/'kea_animated.glb').write_bytes(raw)
out=GLB(D/'kea_animated.glb');newattrs=out.j['meshes'][0]['primitives'][0]['attributes'];oldattrs=base['meshes'][0]['primitives'][0]['attributes'];report={'standalone':True,'approvedBasePositionBytesExact':out.acc(newattrs['POSITION']).tobytes()==P.tobytes(),'approvedBaseNormalBytesExact':out.acc(newattrs['NORMAL']).tobytes()==N.tobytes(),'originalNodesExact':doc['nodes']==base['nodes'],'originalSkinsExact':doc['skins']==base['skins'],'originalBinaryPrefixExact':bytes(binary[:len(g.bin)])==g.bin,'originalAnimationExact':doc['animations'][0]==base['animations'][0],'UVAndSkinWeightAccessorBindingsExact':all(newattrs[k]==v for k,v in oldattrs.items()if k not in ['POSITION','NORMAL']),'originalIndexAccessorExact':prim['indices']==base['meshes'][0]['primitives'][0]['indices'],'materialsTexturesImagesExact':all(doc[k]==base[k]for k in ['materials','textures','images']),'jointCount':len(base['skins'][0]['joints']),'triangleCount':len(g.acc(prim['indices']).ravel())//3,'addedClips':exports,'newMorphTargets':['flight_wing_release'],'morphScope':'Only existing POSITION/NORMAL values; no topology, UV, skin weight or rig changes. Ground base is the exact approved evaluated shape.','fileSha256':hashlib.sha256(raw).hexdigest(),'flightPositionMaxError':float(abs((P+out.acc(prim['targets'][0]['POSITION']))-pf).max())}
assert all(v for k,v in report.items()if isinstance(v,bool));assert report['flightPositionMaxError']<1e-5;(D/'GLB_VALIDATION.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
(D/'APPROVED_IDLE.json').write_text(json.dumps(idle,separators=(',',':')))
